pub struct SurahMeta {
    pub number: u8,
    pub name_arabic: &'static str,
    pub name_transliterated: &'static str,
    pub name_meaning: &'static str,
    pub is_meccan: bool,
    pub revelation_order: u8,
    pub ayah_count: u16,
}

pub const SURAH_META: [SurahMeta; 114] = [
    SurahMeta {
        number: 1,
        name_arabic: "الفاتحة",
        name_transliterated: "Al-Fatihah",
        name_meaning: "The Opening",
        is_meccan: true,
        revelation_order: 5,
        ayah_count: 7,
    },
    SurahMeta {
        number: 2,
        name_arabic: "البقرة",
        name_transliterated: "Al-Baqarah",
        name_meaning: "The Cow",
        is_meccan: false,
        revelation_order: 87,
        ayah_count: 286,
    },
    SurahMeta {
        number: 3,
        name_arabic: "آل عمران",
        name_transliterated: "Ali 'Imran",
        name_meaning: "Family of Imran",
        is_meccan: false,
        revelation_order: 89,
        ayah_count: 200,
    },
    SurahMeta {
        number: 4,
        name_arabic: "النساء",
        name_transliterated: "An-Nisa",
        name_meaning: "The Women",
        is_meccan: false,
        revelation_order: 92,
        ayah_count: 176,
    },
    SurahMeta {
        number: 5,
        name_arabic: "المائدة",
        name_transliterated: "Al-Ma'idah",
        name_meaning: "The Table Spread",
        is_meccan: false,
        revelation_order: 112,
        ayah_count: 120,
    },
    SurahMeta {
        number: 6,
        name_arabic: "الأنعام",
        name_transliterated: "Al-An'am",
        name_meaning: "The Cattle",
        is_meccan: true,
        revelation_order: 55,
        ayah_count: 165,
    },
    SurahMeta {
        number: 7,
        name_arabic: "الأعراف",
        name_transliterated: "Al-A'raf",
        name_meaning: "The Heights",
        is_meccan: true,
        revelation_order: 39,
        ayah_count: 206,
    },
    SurahMeta {
        number: 8,
        name_arabic: "الأنفال",
        name_transliterated: "Al-Anfal",
        name_meaning: "The Spoils of War",
        is_meccan: false,
        revelation_order: 88,
        ayah_count: 75,
    },
    SurahMeta {
        number: 9,
        name_arabic: "التوبة",
        name_transliterated: "At-Tawbah",
        name_meaning: "The Repentance",
        is_meccan: false,
        revelation_order: 113,
        ayah_count: 129,
    },
    SurahMeta {
        number: 10,
        name_arabic: "يونس",
        name_transliterated: "Yunus",
        name_meaning: "Jonah",
        is_meccan: true,
        revelation_order: 51,
        ayah_count: 109,
    },
    SurahMeta {
        number: 11,
        name_arabic: "هود",
        name_transliterated: "Hud",
        name_meaning: "Hud",
        is_meccan: true,
        revelation_order: 52,
        ayah_count: 123,
    },
    SurahMeta {
        number: 12,
        name_arabic: "يوسف",
        name_transliterated: "Yusuf",
        name_meaning: "Joseph",
        is_meccan: true,
        revelation_order: 53,
        ayah_count: 111,
    },
    SurahMeta {
        number: 13,
        name_arabic: "الرعد",
        name_transliterated: "Ar-Ra'd",
        name_meaning: "The Thunder",
        is_meccan: false,
        revelation_order: 96,
        ayah_count: 43,
    },
    SurahMeta {
        number: 14,
        name_arabic: "ابراهيم",
        name_transliterated: "Ibrahim",
        name_meaning: "Abraham",
        is_meccan: true,
        revelation_order: 72,
        ayah_count: 52,
    },
    SurahMeta {
        number: 15,
        name_arabic: "الحجر",
        name_transliterated: "Al-Hijr",
        name_meaning: "The Rocky Tract",
        is_meccan: true,
        revelation_order: 54,
        ayah_count: 99,
    },
    SurahMeta {
        number: 16,
        name_arabic: "النحل",
        name_transliterated: "An-Nahl",
        name_meaning: "The Bee",
        is_meccan: true,
        revelation_order: 70,
        ayah_count: 128,
    },
    SurahMeta {
        number: 17,
        name_arabic: "الإسراء",
        name_transliterated: "Al-Isra",
        name_meaning: "The Night Journey",
        is_meccan: true,
        revelation_order: 50,
        ayah_count: 111,
    },
    SurahMeta {
        number: 18,
        name_arabic: "الكهف",
        name_transliterated: "Al-Kahf",
        name_meaning: "The Cave",
        is_meccan: true,
        revelation_order: 69,
        ayah_count: 110,
    },
    SurahMeta {
        number: 19,
        name_arabic: "مريم",
        name_transliterated: "Maryam",
        name_meaning: "Mary",
        is_meccan: true,
        revelation_order: 44,
        ayah_count: 98,
    },
    SurahMeta {
        number: 20,
        name_arabic: "طه",
        name_transliterated: "Taha",
        name_meaning: "Ta-Ha",
        is_meccan: true,
        revelation_order: 45,
        ayah_count: 135,
    },
    SurahMeta {
        number: 21,
        name_arabic: "الأنبياء",
        name_transliterated: "Al-Anbya",
        name_meaning: "The Prophets",
        is_meccan: true,
        revelation_order: 73,
        ayah_count: 112,
    },
    SurahMeta {
        number: 22,
        name_arabic: "الحج",
        name_transliterated: "Al-Hajj",
        name_meaning: "The Pilgrimage",
        is_meccan: false,
        revelation_order: 103,
        ayah_count: 78,
    },
    SurahMeta {
        number: 23,
        name_arabic: "المؤمنون",
        name_transliterated: "Al-Mu'minun",
        name_meaning: "The Believers",
        is_meccan: true,
        revelation_order: 74,
        ayah_count: 118,
    },
    SurahMeta {
        number: 24,
        name_arabic: "النور",
        name_transliterated: "An-Nur",
        name_meaning: "The Light",
        is_meccan: false,
        revelation_order: 102,
        ayah_count: 64,
    },
    SurahMeta {
        number: 25,
        name_arabic: "الفرقان",
        name_transliterated: "Al-Furqan",
        name_meaning: "The Criterion",
        is_meccan: true,
        revelation_order: 42,
        ayah_count: 77,
    },
    SurahMeta {
        number: 26,
        name_arabic: "الشعراء",
        name_transliterated: "Ash-Shu'ara",
        name_meaning: "The Poets",
        is_meccan: true,
        revelation_order: 47,
        ayah_count: 227,
    },
    SurahMeta {
        number: 27,
        name_arabic: "النمل",
        name_transliterated: "An-Naml",
        name_meaning: "The Ant",
        is_meccan: true,
        revelation_order: 48,
        ayah_count: 93,
    },
    SurahMeta {
        number: 28,
        name_arabic: "القصص",
        name_transliterated: "Al-Qasas",
        name_meaning: "The Stories",
        is_meccan: true,
        revelation_order: 49,
        ayah_count: 88,
    },
    SurahMeta {
        number: 29,
        name_arabic: "العنكبوت",
        name_transliterated: "Al-'Ankabut",
        name_meaning: "The Spider",
        is_meccan: true,
        revelation_order: 85,
        ayah_count: 69,
    },
    SurahMeta {
        number: 30,
        name_arabic: "الروم",
        name_transliterated: "Ar-Rum",
        name_meaning: "The Romans",
        is_meccan: true,
        revelation_order: 84,
        ayah_count: 60,
    },
    SurahMeta {
        number: 31,
        name_arabic: "لقمان",
        name_transliterated: "Luqman",
        name_meaning: "Luqman",
        is_meccan: true,
        revelation_order: 57,
        ayah_count: 34,
    },
    SurahMeta {
        number: 32,
        name_arabic: "السجدة",
        name_transliterated: "As-Sajdah",
        name_meaning: "The Prostration",
        is_meccan: true,
        revelation_order: 75,
        ayah_count: 30,
    },
    SurahMeta {
        number: 33,
        name_arabic: "الأحزاب",
        name_transliterated: "Al-Ahzab",
        name_meaning: "The Combined Forces",
        is_meccan: false,
        revelation_order: 90,
        ayah_count: 73,
    },
    SurahMeta {
        number: 34,
        name_arabic: "سبإ",
        name_transliterated: "Saba",
        name_meaning: "Sheba",
        is_meccan: true,
        revelation_order: 58,
        ayah_count: 54,
    },
    SurahMeta {
        number: 35,
        name_arabic: "فاطر",
        name_transliterated: "Fatir",
        name_meaning: "Originator",
        is_meccan: true,
        revelation_order: 43,
        ayah_count: 45,
    },
    SurahMeta {
        number: 36,
        name_arabic: "يس",
        name_transliterated: "Ya-Sin",
        name_meaning: "Ya Sin",
        is_meccan: true,
        revelation_order: 41,
        ayah_count: 83,
    },
    SurahMeta {
        number: 37,
        name_arabic: "الصافات",
        name_transliterated: "As-Saffat",
        name_meaning: "Those who set the Ranks",
        is_meccan: true,
        revelation_order: 56,
        ayah_count: 182,
    },
    SurahMeta {
        number: 38,
        name_arabic: "ص",
        name_transliterated: "Sad",
        name_meaning: "The Letter \"Saad\"",
        is_meccan: true,
        revelation_order: 38,
        ayah_count: 88,
    },
    SurahMeta {
        number: 39,
        name_arabic: "الزمر",
        name_transliterated: "Az-Zumar",
        name_meaning: "The Troops",
        is_meccan: true,
        revelation_order: 59,
        ayah_count: 75,
    },
    SurahMeta {
        number: 40,
        name_arabic: "غافر",
        name_transliterated: "Ghafir",
        name_meaning: "The Forgiver",
        is_meccan: true,
        revelation_order: 60,
        ayah_count: 85,
    },
    SurahMeta {
        number: 41,
        name_arabic: "فصلت",
        name_transliterated: "Fussilat",
        name_meaning: "Explained in Detail",
        is_meccan: true,
        revelation_order: 61,
        ayah_count: 54,
    },
    SurahMeta {
        number: 42,
        name_arabic: "الشورى",
        name_transliterated: "Ash-Shuraa",
        name_meaning: "The Consultation",
        is_meccan: true,
        revelation_order: 62,
        ayah_count: 53,
    },
    SurahMeta {
        number: 43,
        name_arabic: "الزخرف",
        name_transliterated: "Az-Zukhruf",
        name_meaning: "The Ornaments of Gold",
        is_meccan: true,
        revelation_order: 63,
        ayah_count: 89,
    },
    SurahMeta {
        number: 44,
        name_arabic: "الدخان",
        name_transliterated: "Ad-Dukhan",
        name_meaning: "The Smoke",
        is_meccan: true,
        revelation_order: 64,
        ayah_count: 59,
    },
    SurahMeta {
        number: 45,
        name_arabic: "الجاثية",
        name_transliterated: "Al-Jathiyah",
        name_meaning: "The Crouching",
        is_meccan: true,
        revelation_order: 65,
        ayah_count: 37,
    },
    SurahMeta {
        number: 46,
        name_arabic: "الأحقاف",
        name_transliterated: "Al-Ahqaf",
        name_meaning: "The Wind-Curved Sandhills",
        is_meccan: true,
        revelation_order: 66,
        ayah_count: 35,
    },
    SurahMeta {
        number: 47,
        name_arabic: "محمد",
        name_transliterated: "Muhammad",
        name_meaning: "Muhammad",
        is_meccan: false,
        revelation_order: 95,
        ayah_count: 38,
    },
    SurahMeta {
        number: 48,
        name_arabic: "الفتح",
        name_transliterated: "Al-Fath",
        name_meaning: "The Victory",
        is_meccan: false,
        revelation_order: 111,
        ayah_count: 29,
    },
    SurahMeta {
        number: 49,
        name_arabic: "الحجرات",
        name_transliterated: "Al-Hujurat",
        name_meaning: "The Rooms",
        is_meccan: false,
        revelation_order: 106,
        ayah_count: 18,
    },
    SurahMeta {
        number: 50,
        name_arabic: "ق",
        name_transliterated: "Qaf",
        name_meaning: "The Letter \"Qaf\"",
        is_meccan: true,
        revelation_order: 34,
        ayah_count: 45,
    },
    SurahMeta {
        number: 51,
        name_arabic: "الذاريات",
        name_transliterated: "Adh-Dhariyat",
        name_meaning: "The Winnowing Winds",
        is_meccan: true,
        revelation_order: 67,
        ayah_count: 60,
    },
    SurahMeta {
        number: 52,
        name_arabic: "الطور",
        name_transliterated: "At-Tur",
        name_meaning: "The Mount",
        is_meccan: true,
        revelation_order: 76,
        ayah_count: 49,
    },
    SurahMeta {
        number: 53,
        name_arabic: "النجم",
        name_transliterated: "An-Najm",
        name_meaning: "The Star",
        is_meccan: true,
        revelation_order: 23,
        ayah_count: 62,
    },
    SurahMeta {
        number: 54,
        name_arabic: "القمر",
        name_transliterated: "Al-Qamar",
        name_meaning: "The Moon",
        is_meccan: true,
        revelation_order: 37,
        ayah_count: 55,
    },
    SurahMeta {
        number: 55,
        name_arabic: "الرحمن",
        name_transliterated: "Ar-Rahman",
        name_meaning: "The Beneficent",
        is_meccan: false,
        revelation_order: 97,
        ayah_count: 78,
    },
    SurahMeta {
        number: 56,
        name_arabic: "الواقعة",
        name_transliterated: "Al-Waqi'ah",
        name_meaning: "The Inevitable",
        is_meccan: true,
        revelation_order: 46,
        ayah_count: 96,
    },
    SurahMeta {
        number: 57,
        name_arabic: "الحديد",
        name_transliterated: "Al-Hadid",
        name_meaning: "The Iron",
        is_meccan: false,
        revelation_order: 94,
        ayah_count: 29,
    },
    SurahMeta {
        number: 58,
        name_arabic: "المجادلة",
        name_transliterated: "Al-Mujadila",
        name_meaning: "The Pleading Woman",
        is_meccan: false,
        revelation_order: 105,
        ayah_count: 22,
    },
    SurahMeta {
        number: 59,
        name_arabic: "الحشر",
        name_transliterated: "Al-Hashr",
        name_meaning: "The Exile",
        is_meccan: false,
        revelation_order: 101,
        ayah_count: 24,
    },
    SurahMeta {
        number: 60,
        name_arabic: "الممتحنة",
        name_transliterated: "Al-Mumtahanah",
        name_meaning: "She that is to be examined",
        is_meccan: false,
        revelation_order: 91,
        ayah_count: 13,
    },
    SurahMeta {
        number: 61,
        name_arabic: "الصف",
        name_transliterated: "As-Saf",
        name_meaning: "The Ranks",
        is_meccan: false,
        revelation_order: 109,
        ayah_count: 14,
    },
    SurahMeta {
        number: 62,
        name_arabic: "الجمعة",
        name_transliterated: "Al-Jumu'ah",
        name_meaning: "The Congregation, Friday",
        is_meccan: false,
        revelation_order: 110,
        ayah_count: 11,
    },
    SurahMeta {
        number: 63,
        name_arabic: "المنافقون",
        name_transliterated: "Al-Munafiqun",
        name_meaning: "The Hypocrites",
        is_meccan: false,
        revelation_order: 104,
        ayah_count: 11,
    },
    SurahMeta {
        number: 64,
        name_arabic: "التغابن",
        name_transliterated: "At-Taghabun",
        name_meaning: "The Mutual Disillusion",
        is_meccan: false,
        revelation_order: 108,
        ayah_count: 18,
    },
    SurahMeta {
        number: 65,
        name_arabic: "الطلاق",
        name_transliterated: "At-Talaq",
        name_meaning: "The Divorce",
        is_meccan: false,
        revelation_order: 99,
        ayah_count: 12,
    },
    SurahMeta {
        number: 66,
        name_arabic: "التحريم",
        name_transliterated: "At-Tahrim",
        name_meaning: "The Prohibition",
        is_meccan: false,
        revelation_order: 107,
        ayah_count: 12,
    },
    SurahMeta {
        number: 67,
        name_arabic: "الملك",
        name_transliterated: "Al-Mulk",
        name_meaning: "The Sovereignty",
        is_meccan: true,
        revelation_order: 77,
        ayah_count: 30,
    },
    SurahMeta {
        number: 68,
        name_arabic: "القلم",
        name_transliterated: "Al-Qalam",
        name_meaning: "The Pen",
        is_meccan: true,
        revelation_order: 2,
        ayah_count: 52,
    },
    SurahMeta {
        number: 69,
        name_arabic: "الحاقة",
        name_transliterated: "Al-Haqqah",
        name_meaning: "The Reality",
        is_meccan: true,
        revelation_order: 78,
        ayah_count: 52,
    },
    SurahMeta {
        number: 70,
        name_arabic: "المعارج",
        name_transliterated: "Al-Ma'arij",
        name_meaning: "The Ascending Stairways",
        is_meccan: true,
        revelation_order: 79,
        ayah_count: 44,
    },
    SurahMeta {
        number: 71,
        name_arabic: "نوح",
        name_transliterated: "Nuh",
        name_meaning: "Noah",
        is_meccan: true,
        revelation_order: 71,
        ayah_count: 28,
    },
    SurahMeta {
        number: 72,
        name_arabic: "الجن",
        name_transliterated: "Al-Jinn",
        name_meaning: "The Jinn",
        is_meccan: true,
        revelation_order: 40,
        ayah_count: 28,
    },
    SurahMeta {
        number: 73,
        name_arabic: "المزمل",
        name_transliterated: "Al-Muzzammil",
        name_meaning: "The Enshrouded One",
        is_meccan: true,
        revelation_order: 3,
        ayah_count: 20,
    },
    SurahMeta {
        number: 74,
        name_arabic: "المدثر",
        name_transliterated: "Al-Muddaththir",
        name_meaning: "The Cloaked One",
        is_meccan: true,
        revelation_order: 4,
        ayah_count: 56,
    },
    SurahMeta {
        number: 75,
        name_arabic: "القيامة",
        name_transliterated: "Al-Qiyamah",
        name_meaning: "The Resurrection",
        is_meccan: true,
        revelation_order: 31,
        ayah_count: 40,
    },
    SurahMeta {
        number: 76,
        name_arabic: "الانسان",
        name_transliterated: "Al-Insan",
        name_meaning: "The Man",
        is_meccan: false,
        revelation_order: 98,
        ayah_count: 31,
    },
    SurahMeta {
        number: 77,
        name_arabic: "المرسلات",
        name_transliterated: "Al-Mursalat",
        name_meaning: "The Emissaries",
        is_meccan: true,
        revelation_order: 33,
        ayah_count: 50,
    },
    SurahMeta {
        number: 78,
        name_arabic: "النبإ",
        name_transliterated: "An-Naba",
        name_meaning: "The Tidings",
        is_meccan: true,
        revelation_order: 80,
        ayah_count: 40,
    },
    SurahMeta {
        number: 79,
        name_arabic: "النازعات",
        name_transliterated: "An-Nazi'at",
        name_meaning: "Those who drag forth",
        is_meccan: true,
        revelation_order: 81,
        ayah_count: 46,
    },
    SurahMeta {
        number: 80,
        name_arabic: "عبس",
        name_transliterated: "'Abasa",
        name_meaning: "He Frowned",
        is_meccan: true,
        revelation_order: 24,
        ayah_count: 42,
    },
    SurahMeta {
        number: 81,
        name_arabic: "التكوير",
        name_transliterated: "At-Takwir",
        name_meaning: "The Overthrowing",
        is_meccan: true,
        revelation_order: 7,
        ayah_count: 29,
    },
    SurahMeta {
        number: 82,
        name_arabic: "الإنفطار",
        name_transliterated: "Al-Infitar",
        name_meaning: "The Cleaving",
        is_meccan: true,
        revelation_order: 82,
        ayah_count: 19,
    },
    SurahMeta {
        number: 83,
        name_arabic: "المطففين",
        name_transliterated: "Al-Mutaffifin",
        name_meaning: "The Defrauding",
        is_meccan: true,
        revelation_order: 86,
        ayah_count: 36,
    },
    SurahMeta {
        number: 84,
        name_arabic: "الإنشقاق",
        name_transliterated: "Al-Inshiqaq",
        name_meaning: "The Sundering",
        is_meccan: true,
        revelation_order: 83,
        ayah_count: 25,
    },
    SurahMeta {
        number: 85,
        name_arabic: "البروج",
        name_transliterated: "Al-Buruj",
        name_meaning: "The Mansions of the Stars",
        is_meccan: true,
        revelation_order: 27,
        ayah_count: 22,
    },
    SurahMeta {
        number: 86,
        name_arabic: "الطارق",
        name_transliterated: "At-Tariq",
        name_meaning: "The Nightcommer",
        is_meccan: true,
        revelation_order: 36,
        ayah_count: 17,
    },
    SurahMeta {
        number: 87,
        name_arabic: "الأعلى",
        name_transliterated: "Al-A'la",
        name_meaning: "The Most High",
        is_meccan: true,
        revelation_order: 8,
        ayah_count: 19,
    },
    SurahMeta {
        number: 88,
        name_arabic: "الغاشية",
        name_transliterated: "Al-Ghashiyah",
        name_meaning: "The Overwhelming",
        is_meccan: true,
        revelation_order: 68,
        ayah_count: 26,
    },
    SurahMeta {
        number: 89,
        name_arabic: "الفجر",
        name_transliterated: "Al-Fajr",
        name_meaning: "The Dawn",
        is_meccan: true,
        revelation_order: 10,
        ayah_count: 30,
    },
    SurahMeta {
        number: 90,
        name_arabic: "البلد",
        name_transliterated: "Al-Balad",
        name_meaning: "The City",
        is_meccan: true,
        revelation_order: 35,
        ayah_count: 20,
    },
    SurahMeta {
        number: 91,
        name_arabic: "الشمس",
        name_transliterated: "Ash-Shams",
        name_meaning: "The Sun",
        is_meccan: true,
        revelation_order: 26,
        ayah_count: 15,
    },
    SurahMeta {
        number: 92,
        name_arabic: "الليل",
        name_transliterated: "Al-Layl",
        name_meaning: "The Night",
        is_meccan: true,
        revelation_order: 9,
        ayah_count: 21,
    },
    SurahMeta {
        number: 93,
        name_arabic: "الضحى",
        name_transliterated: "Ad-Duhaa",
        name_meaning: "The Morning Hours",
        is_meccan: true,
        revelation_order: 11,
        ayah_count: 11,
    },
    SurahMeta {
        number: 94,
        name_arabic: "الشرح",
        name_transliterated: "Ash-Sharh",
        name_meaning: "The Relief",
        is_meccan: true,
        revelation_order: 12,
        ayah_count: 8,
    },
    SurahMeta {
        number: 95,
        name_arabic: "التين",
        name_transliterated: "At-Tin",
        name_meaning: "The Fig",
        is_meccan: true,
        revelation_order: 28,
        ayah_count: 8,
    },
    SurahMeta {
        number: 96,
        name_arabic: "العلق",
        name_transliterated: "Al-'Alaq",
        name_meaning: "The Clot",
        is_meccan: true,
        revelation_order: 1,
        ayah_count: 19,
    },
    SurahMeta {
        number: 97,
        name_arabic: "القدر",
        name_transliterated: "Al-Qadr",
        name_meaning: "The Power",
        is_meccan: true,
        revelation_order: 25,
        ayah_count: 5,
    },
    SurahMeta {
        number: 98,
        name_arabic: "البينة",
        name_transliterated: "Al-Bayyinah",
        name_meaning: "The Clear Proof",
        is_meccan: false,
        revelation_order: 100,
        ayah_count: 8,
    },
    SurahMeta {
        number: 99,
        name_arabic: "الزلزلة",
        name_transliterated: "Az-Zalzalah",
        name_meaning: "The Earthquake",
        is_meccan: false,
        revelation_order: 93,
        ayah_count: 8,
    },
    SurahMeta {
        number: 100,
        name_arabic: "العاديات",
        name_transliterated: "Al-'Adiyat",
        name_meaning: "The Courser",
        is_meccan: true,
        revelation_order: 14,
        ayah_count: 11,
    },
    SurahMeta {
        number: 101,
        name_arabic: "القارعة",
        name_transliterated: "Al-Qari'ah",
        name_meaning: "The Calamity",
        is_meccan: true,
        revelation_order: 30,
        ayah_count: 11,
    },
    SurahMeta {
        number: 102,
        name_arabic: "التكاثر",
        name_transliterated: "At-Takathur",
        name_meaning: "The Rivalry in world increase",
        is_meccan: true,
        revelation_order: 16,
        ayah_count: 8,
    },
    SurahMeta {
        number: 103,
        name_arabic: "العصر",
        name_transliterated: "Al-'Asr",
        name_meaning: "The Declining Day",
        is_meccan: true,
        revelation_order: 13,
        ayah_count: 3,
    },
    SurahMeta {
        number: 104,
        name_arabic: "الهمزة",
        name_transliterated: "Al-Humazah",
        name_meaning: "The Traducer",
        is_meccan: true,
        revelation_order: 32,
        ayah_count: 9,
    },
    SurahMeta {
        number: 105,
        name_arabic: "الفيل",
        name_transliterated: "Al-Fil",
        name_meaning: "The Elephant",
        is_meccan: true,
        revelation_order: 19,
        ayah_count: 5,
    },
    SurahMeta {
        number: 106,
        name_arabic: "قريش",
        name_transliterated: "Quraysh",
        name_meaning: "Quraysh",
        is_meccan: true,
        revelation_order: 29,
        ayah_count: 4,
    },
    SurahMeta {
        number: 107,
        name_arabic: "الماعون",
        name_transliterated: "Al-Ma'un",
        name_meaning: "The Small kindnesses",
        is_meccan: true,
        revelation_order: 17,
        ayah_count: 7,
    },
    SurahMeta {
        number: 108,
        name_arabic: "الكوثر",
        name_transliterated: "Al-Kawthar",
        name_meaning: "The Abundance",
        is_meccan: true,
        revelation_order: 15,
        ayah_count: 3,
    },
    SurahMeta {
        number: 109,
        name_arabic: "الكافرون",
        name_transliterated: "Al-Kafirun",
        name_meaning: "The Disbelievers",
        is_meccan: true,
        revelation_order: 18,
        ayah_count: 6,
    },
    SurahMeta {
        number: 110,
        name_arabic: "النصر",
        name_transliterated: "An-Nasr",
        name_meaning: "The Divine Support",
        is_meccan: false,
        revelation_order: 114,
        ayah_count: 3,
    },
    SurahMeta {
        number: 111,
        name_arabic: "المسد",
        name_transliterated: "Al-Masad",
        name_meaning: "The Palm Fiber",
        is_meccan: true,
        revelation_order: 6,
        ayah_count: 5,
    },
    SurahMeta {
        number: 112,
        name_arabic: "الإخلاص",
        name_transliterated: "Al-Ikhlas",
        name_meaning: "The Sincerity",
        is_meccan: true,
        revelation_order: 22,
        ayah_count: 4,
    },
    SurahMeta {
        number: 113,
        name_arabic: "الفلق",
        name_transliterated: "Al-Falaq",
        name_meaning: "The Daybreak",
        is_meccan: true,
        revelation_order: 20,
        ayah_count: 5,
    },
    SurahMeta {
        number: 114,
        name_arabic: "الناس",
        name_transliterated: "An-Nas",
        name_meaning: "Mankind",
        is_meccan: true,
        revelation_order: 21,
        ayah_count: 6,
    },
];
